version: "3.9"

services:
  db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=cms
      - POSTGRES_PASSWORD=cms
      - POSTGRES_DB=cms
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    profiles: ["db"]

volumes:
  db:
    driver: local
